### ISSUE TITLE
Different phaser version in package.json and yarn.lock

### ISSUE THREAD

**Issue by clerie** [workadventure-xce/workadventure-xce#13]
There is a different phaser version in package.json and yarn.lock in the front package. This results to issues when packaging for NixOS.

**Comment by pizkaz** [comment]
Thx for debugging that! :-)

I'm not exactly a yarn wizard... How do I fix yarn.lock?

**Comment by pizkaz** [comment]
I think I got it: `yarn install` did the trick.

**Comment by pizkaz** [comment]
Could you pull again and verify it is fixed? :-)

**Comment by tabascoeye** [comment]
@clerie please check

**Comment by clerie** [comment]
Thank you and sorry, but I'm a bit busy right now. Hope I can try it soon.

**Comment by clerie** [comment]
Ok, thank you. It works now :+1:

**Comment by clerie** [comment]
Hej, I found out now, the same issue exist in the unfederated branch too.

**Comment by pizkaz** [comment]
Hmm, curious... Are you sure you are using (and cleanly (re-)building!) the latest version of the unfederated branch (bf6b6055)? It should contain the same fix as the federated one.

**Comment by clerie** [comment]
Oh sorry for being too tired. Yes, using the current version actually helped.

**Comment by pizkaz** [comment]
Haha, no problem. :-D
