### ISSUE TITLE
"Select your compagnion" scene not touch optimized

### ISSUE THREAD

**Issue by h3ndrik** [workadventure-xce/workadventure-xce#15]
I can't log in from a mobile device because the selection scene for the compagnion requires to press the enter key.

The compagnion patch should also be extended to "Touch here or press enter to start" to make everything work on mobile again.

**Comment by tabascoeye** [comment]
The companion-select screen is no longer part of the default login workflow. So your main problem no longer exists.
Touch support is being worked on. I think I will refacor all the login scenes to make touch support better
