### ISSUE TITLE
Make docker-compose.prod.singledomain.yaml more similar to docker-compose.prod.yaml

### ISSUE THREAD

**Issue by jstsmthrgk** [workadventure-xce/workadventure-xce#2]
There is some difference in the naming of the environment variables in `docker-compose.prod.singledomain.yaml` and `docker-compose.prod.yaml`

I propose changing `BASE_DOMAIN` to `DOMAIN` in `docker-compose.prod.singledomain.yaml`

**Comment by tabascoeye** [comment]
The difference is intentional.
BASE_DOMAIN is used in the Dockerfile of the "front" container to achieve the single-domain use. While DOMAIN is not used anywhere but only in the prod docker-compose file.

This might be better documented and I'm open for suggestions. Close?

**Comment by jstsmthrgk** [comment]
resolved with same reason as #3
