### ISSUE TITLE
local playVideo url is not relative to the maps root (differs from playAudio url)

### ISSUE THREAD

**Issue by Wikinaut** [workadventure-xce/workadventure-xce#22]
I tested the new ```playvideo``` property in ```myworld``` and found that this was not working when only indicating ```mp4/video.mp4``` for an mp4 file stored in ```workadventure-xce/maps/myworld/mp4/video.mp4```. 

I had to define explicitly the full local path, e.g. ```maps/myworld/mp4/video.mp4``` In that way ````playVideo```` currently differs from the use of the ````playAudio```` which I regard as a bug.

Please harmonise the url path definition.

**Comment by tabascoeye** [comment]
yes. apparently ````VideoManager.ts```` doesn't handle the URLs the same as the ````AudioManager````:
https://github.com/workadventure-xce/workadventure-xce/blob/1e03e4db4b80ccc16b0d0bd009de0bdf08a85463/front/src/WebRtc/AudioManager.ts#L55

so this has to be adapted into the VideoManager as well

**Comment by pizkaz** [comment]
The videoplayer feature will be dropped as WA now has a better one.
