### ISSUE TITLE
playVideo / Videoplayer cueing (forward, backward navigation) does not work

### ISSUE THREAD

**Issue by Wikinaut** [workadventure-xce/workadventure-xce#23]
Cueing does not work in Chromium Version 89.0.4389.128 and Firefox 87.0.
When you stop and start again at a new position, the position cursor jumps to end, and the video cannot be played any more.

**Comment by Wikinaut** [comment]
The problem becomes immediately apparent when you click onto `pause` and `play`again.

**Comment by tabascoeye** [comment]
looks a bit like this is the culprit:
https://github.com/workadventure-xce/workadventure-xce/blob/1e03e4db4b80ccc16b0d0bd009de0bdf08a85463/front/src/WebRtc/VideoManager.ts#L98
but I don't understand why it is there in the first place. Might need to try it out without that code or ask the people from DigiGes who created the ````playVideo```` patch

**Comment by pizkaz** [comment]
Seems to have sth to do with HLS support. At least it was introduced in 39f6d077c8e31c19266e366e7f210106accaec85.

**Comment by pizkaz** [comment]
The videoplayer feature will be dropped as WA now has a better one.

**Comment by spezi** [comment]
.. as WA now has a better one? I can´t find any solution to play own Videostream initiated by map properties. what do you mean by better one?can you point me in the right direction please ;)

**Comment by tabascoeye** [comment]
@spezi you use this feature https://workadventu.re/map-building/website-in-map.md to integrate any embed-link URL to e.g. youtube or media.ccc.de and anchor it to the map. That makes much more sense in almost any cases than the video player window which moved along with the player

**Comment by spezi** [comment]
ah ok .. I thought I had overlooked something :) thats my current solution too. thanks
