### ISSUE TITLE
Turn Server / Vagrant

### ISSUE THREAD

**Issue by sebkur** [workadventure-xce/workadventure-xce#24]
Hi everyone,

first of all, thanks for your efforts in building this community fork!

I forked your fork and rebased our changes on top of it.
In particular I've been testing things using vagrant to have reproducible settings independent of the host machine. There's some info in the main repo about vagrant already, but maybe somebody finds these bits useful: https://github.com/mobanisto/workadventure-xce/tree/xce-unfederated/vagrant

On a different note, did anybody get a TURN server running already? I installed coturn a while ago and have been trying for ages to get it working with WA properly to accomodate our users behind firewalls but I cannot seem to get it running. I've found this [wonderful tool](https://webrtc.github.io/samples/src/content/peerconnection/trickle-ice/) for testing if it works, but it actually doesn't help me much debugging the situation. Also there seem to be no logs about coturn even though I can see that it is running. I'd be very glad to get in touch with somebody who had success setting up coturn (or other equivalent software) and got it running smoothly with WA.

Thanks,
Sebastian

**Comment by sebkur** [comment]
Found out what was going wrong in my case. I wasn't passing `TURN_STATIC_AUTH_SECRET` to the `back` module in the docker compose, hence the backend didn't know how to compute temporary username/password pairs.
https://github.com/mobanisto/workadventure-xce/commit/6063909061e8f809ad742b322e542479cf689290

**Comment by pizkaz** [comment]
Hmm that's interesting. Did you find out the difference between `TURN_STATIC_AUTH_SECRET` and `TURN_PASSWORD` (which is passed to the front container)?

edit:
I just found https://github.com/workadventure-xce/workadventure-xce/blob/xce/docker-compose.yaml#L36.

So I'm assuming, one needs to configure coturn like so
```
use-auth-secret
static-auth-secret=supers3cre7
```
and `.env` should contain these:
```
TURN_USER=
TURN_PASSWORD=
TURN_STATIC_AUTH_SECRET=supers3cre7
```
Am I on the right track?

So far I've been trying to use a static user/password (coturn: `lt-cred-mech` + `user=...` / WA: `TURN_USER` + `TURN_PASSWORD`) but to no avail. :frowning_face:

**Comment by sebkur** [comment]
I tried static user/password combinations before but didn't get that to work either.

What I did then was setup Jitsi, which was pretty simple and which also sets up a coturn server along the way. I made sure that is working properly. In particular I found it pretty useful to simulate a user that cannot establish a direct connection to have a situation where the coturn server is being used reproducibly. It is possible to make Firefox only go through relays instead of connecting to peers directly. Within Firefox, navigate to `about:config` and toggle the `media.peerconnection.ice.relay_only` to `true`.

So then I knew that coturn works properly using Jitsi and Jitsi configured coturn to use `use-auth-secret` and `static-auth-secret`. Hence I tried to use the same approach. With the Firefox setup I finally found out what was going on. I did a lot of stdout debugging about wheter `TURN_STATIC_AUTH_SECRET` is actually set within the `back` module in the relevant places and thereby found out that it was always unset there. I can recommend to do that too to find out whether your docker-compose config is actually passing on those variables properly.

**Comment by pizkaz** [comment]
> Within Firefox, navigate to `about:config` and toggle the `media.peerconnection.ice.relay_only` to `true`.

Thanks a lot. This is going to help me big time!

> [...] Jitsi configured coturn to use `use-auth-secret` and `static-auth-secret`.

Really? IIRC, it didn't do that on my Server. :thinking:

**Comment by sebkur** [comment]
hmm, maybe you're using different packages? I'm using the Ubuntu packages from here: https://desktop.jitsi.org/Main/Download

**Comment by pizkaz** [comment]
> > [...] Jitsi configured coturn to use `use-auth-secret` and `static-auth-secret`.
> 
> Really? IIRC, it didn't do that on my Server. thinking

Actually, it did. I just messed it up. :stuck_out_tongue_winking_eye:
