### ISSUE TITLE
docker-compose.prod.singledomain.yaml not working

### ISSUE THREAD

**Issue by jstsmthrgk** [workadventure-xce/workadventure-xce#3]
`docker-compose.prod.singledomain.yaml` mounts `acme.json` at `/acme.json`, but expects it at `/letsencrypt/acme.json`, IMO changing it so it expects `/acme.json` makes the most sense, as that is how it is done in `docker-compose.prod.yaml`.

I also propose using `httpchallenge` instead of `tlschallenge`, as `tlschallenge` never worked for me.

**Comment by tabascoeye** [comment]
how does https://github.com/workadventure-xce/workadventure-xce/commit/3eccc3f177bed0e03f2875e14cebdfac239e993a work for you?
