### ISSUE TITLE
Multi-platform revert

### ISSUE THREAD

**Issue by moufmouf** [workadventure-xce/workadventure-xce#32]
Hey @pizkaz!

Just saw you reverted this commit in XCE:

https://github.com/workadventure-xce/workadventure-xce/commit/5b05595c76e7b804cbacc0276d62f16f3cc8497a

Did it break anything particular?

**Comment by pizkaz** [comment]
Yes, it breaks the Docker image build because generated protobuf message files are missing.

**Comment by moufmouf** [comment]
Indeed, because node-grpc does not ship with ARM-64 binaries, we need to generate protobuf messages out of the docker build process (before running "docker build").
Ping @lukashass.

Is this is big issue for you?

**Comment by pizkaz** [comment]
Let's move this discussion to the upstream-PR: https://github.com/thecodingmachine/workadventure/pull/1924
