### ISSUE TITLE
[Suggestion] make "play" (as in play.domain)" a configuration parameter (incl. proposal for pull-request)

### ISSUE THREAD

**Issue by Wikinaut** [workadventure-xce/workadventure-xce#4]
Where to change play.domainname to pixel.domainname (example)

Situation:

I wished to migrate away from "play.subdomainname" to something else, in the concrete example, my domain for the users will become "pixel.subdomainname" (like pixel.bar.domain.de).

I identified four places which need changes; please allow me to suggest that "play" (or "pixel") serversubdomain name - especially the occurence in front/src/Phaser/Menu/MenuScene.ts - becomes a configuration parameter and prepared a ready-for pull-request branch
https://github.com/Wikinaut/workadventure-xce/tree/chg-play-to-pixel

**Comment by jstsmthrgk** [comment]
Just use `docker-compose.prod.singledomain.yaml` and set `pixel.subdomainname` as `$BASE_DOMAIN`
