### ISSUE TITLE
[tablet controls] Joystick not in the upper most layer - may become fully or partially hidden

### ISSUE THREAD

**Issue by Wikinaut** [workadventure-xce/workadventure-xce#6]
![grafik](https://user-images.githubusercontent.com/1151915/112686579-7713bf00-8e76-11eb-8135-8ac55fcc22f0.png)
![grafik](https://user-images.githubusercontent.com/1151915/112686750-c0640e80-8e76-11eb-95a0-a84fa98ce4d2.png)

test here: https://wa.tabascoeye.de/_/global/raw.githubusercontent.com/ecocurious2/rc3_2020/main/main.json

**Comment by pizkaz** [comment]
It's also broken on current xce branch. Doesn't respond to input anymore.
:-(

**Comment by pizkaz** [comment]
> It's also broken on current xce branch. Doesn't respond to input anymore.
> :-(

Downgrading back to Phaser 0.52.0 "fixes" that one. :-/

**Comment by pizkaz** [comment]
> > It's also broken on current xce branch. Doesn't respond to input anymore.
> > :-(
> 
> Downgrading back to Phaser 0.52.0 "fixes" that one. :-/

So I found a better fix for that. \o/

As for the Joystick not being displayed on top of everything else:
I was thinking: Do we even need a visual representation of the joystick? And for that matter: Must it be explicitly enabled? Why don't we enable "touch & drag" per default and don't show the joystick at all? In an early version the joystick was always positioned in the middle of the screen - it made sense then. But now you can just "touch & drag" anywhere on the screen, so why bother displaying a (btw. quite ugly ^^) joystick?
@tabascoeye

**Comment by tabascoeye** [comment]
I agree, but there is still an unintended bug in WA.
Because the same is true for Nicknames. They are set (as the joystick) to `this.setDepth(99999);` which apparently still only stays on the "floorLayer" level of the map.
==> we could file a bug upstream about that which would eventually also fix the joystick.
But I agree that we should simply enable it always, get rid of the "joystick" setting in the menu altogether and remove the "blob" visual

**Comment by pizkaz** [comment]
Hmm, the "joystick" setting also en-/disables fullscreen mode. Maybe that part is worth keeping..?

**Comment by tabascoeye** [comment]
should be its own setting anyway.

**Comment by pizkaz** [comment]
Done. :-)

Also the fact that names are hidden by layers above `floorLayer` can be seen as a feature: I have seen people play hide&seek. That would be a little pointless if you could always see avatars' names. :-D
