### ISSUE TITLE
Frame handles may overlay action buttons of their embedded websites and make them unreachable

### ISSUE THREAD

**Issue by Wikinaut** [workadventure-xce/workadventure-xce#9]
![grafik](https://user-images.githubusercontent.com/1151915/112717565-e37dd500-8eed-11eb-87a5-8083842cf70a.png)

**Comment by pizkaz** [comment]
This issue is not related to XCE-only features. IMHO it would be better to file this upstream.

**Comment by Wikinaut** [comment]
filed upstream as https://github.com/thecodingmachine/workadventure/issues/850
